version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./todo-project:/app
        command: 
            sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - db
        environment: 
            - DB_HOST=db
            - DB_USER=todo
            - DB_PASSWORD=todo
            - DB_NAME=todo
    db:
        image: postgres:10-alpine
        restart: always
        environment:
            - POSTGRES_PASSWORD=todo
            - POSTGRES_DB=todo
            - POSTGRES_USER=todo